version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: schedule
      RABBITMQ_DEFAULT_PASS: schedule
      RABBITMQ_DEFAULT_VHOST: schedule-service
    ports:
      - "5672:5672"  # Порт для общения с микросервисами
      - "15672:15672" # Web UI для управления RabbitMQ
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - shared-network

  bookingservice:
    container_name: bookingservice
    build:
      dockerfile: Dockerfile
      context: .
    hostname: bookingservice
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hostelDB:5432/hostelService
      - SPRING_DATASOURCE_USERNAME=hostel
      - SPRING_DATASOURCE_PASSWORD=ilia
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 10s
    networks:
      - shared-network

networks:
  shared-network:
    external: true
