name: CI/CD for Jabroni

on:
  push:
    branches:
      - master

jobs:
  cache:
    name: Cache dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

  build:
    name: Build and Tests
    runs-on: ubuntu-latest
    needs: cache
    outputs:
      jar-path: ${{ steps.upload.outputs.artifact-path || '' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Build with Gradle
        env:
          INTERNAL_REPO_LOGIN: ${{ secrets.INTERNAL_REPO_LOGIN }}
          INTERNAL_REPO_PASSWORD: ${{ secrets.INTERNAL_REPO_PASSWORD }}
        run: |
          chmod +x gradlew
          ./gradlew clean build

#      - name: Upload built jar as artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: app-jar
#          path: build/libs/*.jar

  dockerized:
    name: Build and run in Docker
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

#      - name: Download built jar from build job
#        uses: actions/download-artifact@v4
#        with:
#          name: app-jar
#          path: ./build/libs

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker image (single build)
        env:
          INTERNAL_REPO_LOGIN: ${{ secrets.INTERNAL_REPO_LOGIN }}
          INTERNAL_REPO_PASSWORD: ${{ secrets.INTERNAL_REPO_PASSWORD }}
        run: docker-compose -f docker-compose-test.yml up --build -d

      - name: Wait for services to be healthy
        run: |
          echo "Waiting for services to be healthy..."
          sleep 20
          docker ps -a
          docker logs my-app || true

      - name: Stop and remove containers
        run: docker-compose -f docker-compose-test.yml down

  sonar_analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: dockerized
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Build and analyze with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          INTERNAL_REPO_LOGIN: ${{ secrets.INTERNAL_REPO_LOGIN }}
          INTERNAL_REPO_PASSWORD: ${{ secrets.INTERNAL_REPO_PASSWORD }}
        run: |
          chmod +x gradlew
          ./gradlew sonarqube --info
    continue-on-error: true

  deploy:
    name: Deploy on Prod
    runs-on: ubuntu-latest
    needs: dockerized

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

#      - name: Download built jar from build job
#        uses: actions/download-artifact@v4
#        with:
#          name: app-jar
#          path: ./build/libs

      - name: Build and Push Docker Image
        env:
          INTERNAL_REPO_LOGIN: ${{ secrets.INTERNAL_REPO_LOGIN }}
          INTERNAL_REPO_PASSWORD: ${{ secrets.INTERNAL_REPO_PASSWORD }}
        run: |
          IMAGE=ghcr.io/tpabka251/bookingservice
          docker build \
            --build-arg INTERNAL_REPO_LOGIN=${INTERNAL_REPO_LOGIN} \
            --build-arg INTERNAL_REPO_PASSWORD=${INTERNAL_REPO_PASSWORD} \
            -t $IMAGE:latest \
            -t $IMAGE:${{ github.sha }} \
            .
          docker push $IMAGE:latest
          docker push $IMAGE:${{ github.sha }}

      - name: Deploy to k3s via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd Booking
            git pull origin master
            sudo kubectl apply -f k8s/test/deployment.yaml
            sudo kubectl apply -f k8s/test/service.yaml
            sudo kubectl rollout restart deployment/bookingservice
            sudo kubectl rollout status deployment/bookingservice
